### ISSUE TITLE
sample code does not work with https

### ISSUE THREAD

**Issue by kenirwin** [produck/cas-client#2]
I tried using the native Node.js sample code, but our CAS server didn't like that my app was running http instead of https. I tried simply switching to `require('https')` and using:
```
const https_options = {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem')
}

    https.createServer(https_options, (req, res) => {
```

but I get an "unexpected identifier" error regarding "handler" in the `if (!await handler)` line.

Do you have an suggestion for how to use the native https module to work?

Thanks

**Comment by lichaozhy** [comment]
ok, let me have a look

**Comment by Miniland1333** [comment]
@kenirwin in case you haven't solved this in the past year, my guess at the issue is that you are missing `async`, which is why the `await` causes the `unexpected identifier` error.

When comparing what you have pasted above to the example code, you are indeed missing `async`:
```javascript
http.createServer(async (req, res) => {
	if(!await handler(req, res)) {
		return res.end();
	}
...
```

**Comment by lichaozhy** [comment]
@Miniland1333 Are you sure that ``http-cas-client`` is ok using in a https application(as cas-client)? Is there a bug about https?

**Comment by Miniland1333** [comment]
The lack of `async` would likely be the cause of the syntax error `unexpected identifier`. This is because `await` is only valid inside of an `async` function. Your example has `async` in it, but the code that was posted with the issue has it missing.
![image](https://user-images.githubusercontent.com/12994749/103618128-4316a680-4ee4-11eb-820f-61b747f658bf.png)

 It is certainly possible that there may be some additional error with using https, but it is unlikely that just swapping to https would cause this syntactical error.

I think we would need to wait for @kenirwin to confirm whether the quick addition of `async` solves the problem or if the source of the issue is indeed connected to https.

**Comment by kenirwin** [comment]
I'm not sure now -- I switched to using the node-cas-client when I couldn't figure this one out. If you can get it to work for you, perhaps you could add an https sample to the documentation. Thanks!

**Comment by Miniland1333** [comment]
@kenirwin I did some testing this morning with a self-signed certificate this morning and it does seem that the `unexpected identifier` issue was simply due to the missing `async`. Here's the sample code that I was able to run without errors:

```javascript
const https = require('https');
const httpCasClient = require('http-cas-client');
const fs = require('fs');

// A CAS server deployed at url http://localhost:9000.
// Default prefix is '/'.
const handler = httpCasClient({
    casServerUrlPrefix: 'http://localhost:9000/cas',
    serverName: 'http://127.0.0.1'
});

const https_options = {
    key: fs.readFileSync('server.key'),
    cert: fs.readFileSync('server.crt')
}

https.createServer(https_options, async (req, res) => { //this was the line missing async
    if (!await handler(req, res)) {
        return res.end();
    }
    
    const {principal, ticket} = req;
    console.log(principal, ticket);
    // { user: 'test', attributes: { ... } }
    
    // your statements...
    res.end('hello world');
}).listen(443);
```

The success of this test indicates that this issue is related neither to problems with `http-cas-client` nor with `https`, but was instead just a syntactical error.

@lichaozhy, would you like this https example added to your readme, or is it similar enough to the http that it isn't needed? Also, thank you for all the work you've done with this repository! It's ease-of-use makes usage and debugging a breeze.

**Comment by lichaozhy** [comment]
Thx @Miniland1333 & @kenirwin . The issue will be closed.
